@base = http://localhost:3000/api/v1

### createTodo
POST {{base}}/todos
Content-Type: application/json

{
  "title": "Buy milk",
  "description": "2%"
}

### getTodos
@id = <id>
GET {{base}}/todos/{{id}}

### listTodos
GET {{base}}/todos?rank=232&page=43

### putTodo
@id = <id>
PUT {{base}}/todos/{{id}}
Content-Type: application/json

{
  "item": {
    "done": true
  }
}
